INSERT INTO users (name) VALUES ('Kim');
INSERT INTO users (name) VALUES ('Oliver');
INSERT INTO users (name) VALUES ('Pierce');
INSERT INTO users (name) VALUES ('Rochelle');
INSERT INTO users (name) VALUES ('Al');
INSERT INTO users (name) VALUES ('Sam');


INSERT INTO movies (imdb_id, whose_pick, title, date_watched, country, release_year, img_src, synopsis) VALUES ('tt0050083', 4, '12 Angry Men', '2017-10-10', 'USA', 1957, 'https://imdb-api.com/images/original/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_Ratio0.7273_AL_.jpg', 'space filler -  synopsis for 12 angry men');
INSERT INTO movies (imdb_id, whose_pick, title, date_watched, country, release_year, img_src, synopsis) VALUES ('tt0053125', 1, 'North by Northwest', '2017-02-08', 'USA', 1959, 'https://imdb-api.com/images/original/MV5BZDA3NDExMTUtMDlhOC00MmQ5LWExZGUtYmI1NGVlZWI4OWNiXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_Ratio0.7273_AL_.jpg', 'space filler -  synopsis for north by northwest');
INSERT INTO movies (imdb_id, whose_pick, title, date_watched, country, release_year, img_src, synopsis) VALUES ('tt0050083', 4, '12 Angry Men', '2017-10-10', 'USA', 1957, 'https://imdb-api.com/images/original/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_Ratio0.7273_AL_.jpg', 'space filler -  synopsis for 12 angry men');
INSERT INTO movies (imdb_id, whose_pick, title, date_watched, country, release_year, img_src, synopsis) VALUES ('tt0053125', 1, 'North by Northwest', '2017-02-08', 'USA', 1959, 'https://imdb-api.com/images/original/MV5BZDA3NDExMTUtMDlhOC00MmQ5LWExZGUtYmI1NGVlZWI4OWNiXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_Ratio0.7273_AL_.jpg', 'space filler -  synopsis for north by northwest');
INSERT INTO movies (imdb_id, whose_pick, title, date_watched, country, release_year, img_src, synopsis) VALUES ('tt0050083', 4, '12 Angry Men', '2017-10-10', 'USA', 1957, 'https://imdb-api.com/images/original/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_Ratio0.7273_AL_.jpg', 'space filler -  synopsis for 12 angry men');
INSERT INTO movies (imdb_id, whose_pick, title, date_watched, country, release_year, img_src, synopsis) VALUES ('tt0053125', 1, 'North by Northwest', '2017-02-08', 'USA', 1959, 'https://imdb-api.com/images/original/MV5BZDA3NDExMTUtMDlhOC00MmQ5LWExZGUtYmI1NGVlZWI4OWNiXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_Ratio0.7273_AL_.jpg', 'space filler -  synopsis for north by northwest');
INSERT INTO movies (imdb_id, whose_pick, title, date_watched, country, release_year, img_src, synopsis) VALUES ('tt0050083', 4, '12 Angry Men', '2017-10-10', 'USA', 1957, 'https://imdb-api.com/images/original/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_Ratio0.7273_AL_.jpg', 'space filler -  synopsis for 12 angry men');
INSERT INTO movies (imdb_id, whose_pick, title, date_watched, country, release_year, img_src, synopsis) VALUES ('tt0053125', 1, 'North by Northwest', '2017-02-08', 'USA', 1959, 'https://imdb-api.com/images/original/MV5BZDA3NDExMTUtMDlhOC00MmQ5LWExZGUtYmI1NGVlZWI4OWNiXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_Ratio0.7273_AL_.jpg', 'space filler -  synopsis for north by northwest');